name: bigotis
channels:
  - conda-forge
  - anaconda
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.0.221
  - pytorch=1.7.1
  - torchvision=0.8.2
  - flask=1.1.2
  - imageio=2.9.0
  - python=3.7.9
  - pip=21.0.1
  - pip:
    - ftfy==6.0.1
    - regex==2021.4.4
    - tqdm==4.60.0
    - clip==1.0
    - dall-e==0.1
    - imageio-ffmpeg==0.4.3
    - PyYAML==5.4.1
    - omegaconf==2.0.6
    - pytorch-lightning==1.3.3
    - redis==3.4.1
    - rq==1.2.2